### ISSUE TITLE
Chroma channel smoothing

### ISSUE THREAD

**Issue by joppuyo** [joedrago/colorist#22]
Hey,

I don’t know if this is a Colorist issue or with the upstream avif library, but I have noticed that if I convert an image to avif format with 4:2:0 chroma subsampling and convert it back to png, the chroma component is upscaled with nearest neighbor scaling which leads to blocky looking image.

![Image converted with Colorist](https://user-images.githubusercontent.com/1595438/66917852-d7b68f80-f026-11e9-966e-ff60fa568167.png)

This is especially noticeable with red and pink hats. If I view the same image with [avif.js](https://github.com/Kagami/avif.js) library, it seems that a bicubic or bilinear scaling is used for the chroma which looks smoother.

![Image converted with avif.js](https://user-images.githubusercontent.com/1595438/66917894-e9983280-f026-11e9-9bdd-91c5fe153218.png)

If possible, I think it would be good idea to implement similar filtering in Colorist

Thanks!

**Comment by joedrago** [comment]
That is going to be an issue with libavif, which fortunately (unfortunately?) I am also the author. 

The only reason I implemented YUV conversion at all is because at the time of writing, libyuv had no support for 10bpc RGB conversion (which I believe it still might not).

I will look into it and see what I am missing, but I thought I was interpolating correctly for YUV420.

**Comment by joedrago** [comment]
I followed through the path libyuv takes for both directions (RGB <-> YUV420), and I believe I'm doing the exact same math. I'm not sure exactly what Chrome is doing in the avif.js case, but perhaps ffmpeg is doing something clever. I'll check into ffmpeg soon and see what their swscale code does, but so far I'm not finding any obvious wins here.

**Comment by joedrago** [comment]
I'm going to close this one as it is over a year old and since this bug's creation, libavif has gotten proper bilinear upsampling.
