### ISSUE TITLE
Misfunction when converting file with even width to avif

### ISSUE THREAD

**Issue by GrandArth** [joedrago/colorist#34]
![1](https://user-images.githubusercontent.com/30680793/86463088-732b9400-bd5f-11ea-94ef-eec21099724d.png)
This is a white image with size 204 x 227.
![图片](https://user-images.githubusercontent.com/30680793/86463147-8fc7cc00-bd5f-11ea-964b-02c5b5bc9543.png)
This is what i got with
```
colorist convert 1.png 1.avif
```
[1.zip](https://github.com/joedrago/colorist/files/4869318/1.zip)

Any ideas?

**Comment by joedrago** [comment]
I only see this artifact when looking at it in a Windows Explorer thumbnail, and Windows' AVIF decoder doesn't support YUV444 at all yet. If I decode your file with either `avifdec` or `colorist`, they look correct:

    avifdec 1.avif avifdec.png
    colorist convert 1.avif colorist.png

If you want to see it behave, you can use `--yuv 420` (with either tool) and it should stop doing that. Windows appears to be doing something odd with the last row in the 420 case, but `avifdec` and `colorist` both seem to decode that one just fine as well.
