### ISSUE TITLE
Image is just green after convert from bmp to avif

### ISSUE THREAD

**Issue by RozeFound** [joedrago/colorist#36]
All in the title. I just try to convert bmp file to avif with simple command "colorist convert input.bmp output.avif -q 34" and this is what happend:
![image](https://user-images.githubusercontent.com/68745888/90530642-51fff500-e19f-11ea-87e0-5bc880d95d74.png)

**Comment by joedrago** [comment]
Bitmap support isn't really the best, in colorist. I added it to have a simple means to carry around 10bpc pixels + an ICC profile, but I'm sure there are plenty of valid BMP files that colorist will misunderstand.

**Comment by RozeFound** [comment]
So... You will fix this? Or u think this don't needed to fix? If it help, this bmp was generated by ShareX.

**Comment by joedrago** [comment]
I'll happily accept a Pull Request that fixes this.

**Comment by RozeFound** [comment]
I'm not good programmer for do something like this, therefore i just close the issue...
