### ISSUE TITLE
Relative crop position

### ISSUE THREAD

**Issue by S1SYPHOS** [joedrago/colorist#37]
Hey there,
one question, if that's alright: is there an easy way to define crop positions? Like ImageMagick's crop [relative to gravity](http://www.imagemagick.org/Usage/crop/#crop_gravity) - or am I too blind to see how to work around this with `-z` 🦊 

Thanks in advance, have a good day!
S1SYPHOS

**Comment by joedrago** [comment]
Heh, no such thing, sorry. The first two values are the x and y of the top left, and the second two values are the width and height.

**Comment by S1SYPHOS** [comment]
I know .. so then centering would be done by calculating - no biggie.

Would be a comfortable though!
